spring:
  datasource:
    url: jdbc:mysql://dev-ttokttok.cjyuygmyir9b.ap-northeast-2.rds.amazonaws.com:3306/ttokttok
    username: root
    password: ${{secrets.AWS_mySQL_access_key}}
    driver-class-name: com.mysql.cj.jdbc.Driver
  sql:
    init:
      mode: never
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        show_sql: true
        format_sql: true
        use_sql_comments: true
        hbm2ddl:
          auto: create
        default_batch_fetch_size: 1000