spring:
  datasource:
    url: jdbc:mysql://dev-ttokttok.cjyuygmyir9b.ap-northeast-2.rds.amazonaws.com:3306/ttokttok
    username: root
    password: ${{secrets.AWS_mySQL_access_key}}
    driver-class-name: com.mysql.cj.jdbc.Driver
  sql:
    init:
      mode: never
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        show_sql: true
        format_sql: true
        use_sql_comments: true
        hbm2ddl:
          auto: update
        default_batch_fetch_size: 1000
  ai:
    vertex:
      ai:
        gemini:
          # 1. (필수) Google Cloud 프로젝트 ID
          project-id: "gen-lang-client-0133965444"
          # 2. (필수) Vertex AI 리전 (예: us-central1)
          location: "us-central1"
          chat:
            options:
              # 3. 모델명 (요청하신 2.5 Flash)
              model: "gemini-2.5-flash-latest"
              temperature: 0.4